name: Elixir Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

jobs:
  build:
    name: Elixir Unit Tests
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      PGPASSWORD: postgres
    strategy:
      matrix:
        include:
          # Elixir 1.13 doesn't support OTP 26+
          - elixir: '1.13.4'
            otp: '22.3'
          - elixir: '1.13.4'
            otp: '25.3.2'
        # Elixir 1.14 requires at least OTP 23
          - elixir: '1.14.4'
            otp: '23.3.4'
          - elixir: '1.14.4'
            otp: '26.2.5'
          # Elixir 1.15 requires at least OTP 24
          - elixir: '1.15.5'
            otp: '24.3.4'
          - elixir: '1.15.5'
            otp: '26.2.5'
          # Elixir 1.16 requires at least OTP 24
          - elixir: '1.16.2'
            otp: '24.3.4'
          - elixir: '1.16.2'
            otp: '26.2.5'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          build-app: false

      - name: Compile with warnings as errors
        if: ${{ matrix.elixir == '1.16.2' }} 
        run: mix compile --warnings-as-errors

      - name: Run tests with warnings as errors
        if: ${{ matrix.elixir == '1.16.2' }} 
        run: mix test --warnings-as-errors

      - name: Run tests
        if: ${{ matrix.elixir != '1.16.2' }} 
        run: mix test
